/**
 * Ocean Routing provider — our home-grown maritime distance engine.
 *
 * Uses a pre-computed distance table generated by a Python pipeline
 * (0.1° water grid, ~4.5M waypoints, Dijkstra shortest path + hand-drawn
 * overrides for major trade lanes). 106 curated gasoline trading ports,
 * validated against Netpas Distance with ~2% average error.
 *
 * Data pipeline:
 *   scripts/ocean-routing/build_distances.py      — full rebuild (~10 min)
 *   scripts/ocean-routing/apply_hand_drawn.py     — fast override pass
 *   Output lands in scripts/ocean-routing/output/, copied into this folder.
 */

import type {
  DistanceProvider,
} from "../../provider";
import type {
  PortInfo,
  RouteLeg,
  RouteResult,
  PortSearchResult,
  PortAmbiguityResult,
} from "../../types";

import distancesRaw from "./distances.json";
import pathsRaw from "./paths.json";
import handDrawnKeysRaw from "./hand_drawn_keys.json";

const PROVIDER_NAME = "ocean_routing";

// ============================================================
// PORT DATABASE — 106 curated gasoline trading ports
// ============================================================

interface PortEntry {
  name: string;
  lat: number;
  lon: number;
  aliases: string[];
}

const PORTS: PortEntry[] = [
  // ARA
  { name: "Amsterdam, NL", lat: 52.4075, lon: 4.7856, aliases: [] },
  { name: "Rotterdam, NL", lat: 51.9000, lon: 4.4833, aliases: [] },
  { name: "Antwerp, BE", lat: 51.2667, lon: 4.3833, aliases: ["antwerpen"] },
  { name: "Flushing, NL", lat: 51.4500, lon: 3.5833, aliases: ["vlissingen"] },
  { name: "Ghent, BE", lat: 51.0667, lon: 3.7167, aliases: ["gent"] },

  // Med
  { name: "Lavera, FR", lat: 43.3833, lon: 4.9833, aliases: ["fos-sur-mer", "fos"] },
  { name: "Marseille, FR", lat: 43.3000, lon: 5.3667, aliases: [] },
  { name: "Augusta, IT", lat: 37.2167, lon: 15.2167, aliases: [] },
  { name: "Barcelona, ES", lat: 41.3500, lon: 2.1667, aliases: [] },
  { name: "Agioi Theodoroi, GR", lat: 37.9167, lon: 23.0833, aliases: ["agioi theodori"] },
  { name: "Thessaloniki, GR", lat: 40.6167, lon: 22.9333, aliases: ["saloniki"] },
  { name: "Sarroch, IT", lat: 39.0667, lon: 9.0167, aliases: [] },
  { name: "Genoa, IT", lat: 44.4000, lon: 8.9167, aliases: ["genova"] },
  { name: "Naples, IT", lat: 40.8333, lon: 14.2667, aliases: ["napoli"] },
  { name: "Algeciras, ES", lat: 36.1333, lon: -5.4333, aliases: [] },
  { name: "Cartagena, ES", lat: 37.5833, lon: -0.9833, aliases: [] },

  // North Africa / Med South
  { name: "Skikda, DZ", lat: 36.8833, lon: 6.9000, aliases: [] },
  { name: "Mohammedia, MA", lat: 33.7167, lon: -7.3833, aliases: [] },
  { name: "Alexandria, EG", lat: 31.1833, lon: 29.8833, aliases: [] },

  // Baltic / Northern Europe
  { name: "Ust-Luga, RU", lat: 59.6833, lon: 28.3833, aliases: ["ust luga"] },
  { name: "Primorsk, RU", lat: 60.3500, lon: 28.6167, aliases: [] },
  { name: "Sankt-Peterburg, RU", lat: 59.9333, lon: 30.2000, aliases: ["st petersburg", "saint petersburg"] },
  { name: "Gothenburg, SE", lat: 57.7000, lon: 11.9333, aliases: ["goteborg", "göteborg"] },
  { name: "Ventspils, LV", lat: 57.4000, lon: 21.5333, aliases: [] },
  { name: "Gdansk, PL", lat: 54.4000, lon: 18.6667, aliases: [] },
  { name: "Brofjorden, SE", lat: 58.3500, lon: 11.4333, aliases: [] },

  // UK / Ireland
  { name: "Immingham, GB", lat: 53.6333, lon: -0.2167, aliases: [] },
  { name: "Milford Haven, GB", lat: 51.7000, lon: -5.0500, aliases: [] },
  { name: "Fawley, GB", lat: 50.8333, lon: -1.3333, aliases: [] },
  { name: "London, GB", lat: 51.5000, lon: 0.0500, aliases: [] },
  { name: "Belfast, GB", lat: 54.6000, lon: -5.9167, aliases: [] },

  // West Africa
  { name: "Lagos, NG", lat: 6.4333, lon: 3.4000, aliases: ["apapa"] },
  { name: "Lome, TG", lat: 6.1333, lon: 1.2833, aliases: ["lomé"] },
  { name: "Tema, GH", lat: 5.6333, lon: -0.0167, aliases: [] },
  { name: "Abidjan, CI", lat: 5.2667, lon: -4.0167, aliases: [] },
  { name: "Dakar, SN", lat: 14.6667, lon: -17.4167, aliases: [] },
  { name: "Cotonou, BJ", lat: 6.3500, lon: 2.4333, aliases: [] },

  // USA / Caribbean
  { name: "New York, US", lat: 40.6667, lon: -74.0333, aliases: [] },
  { name: "Philadelphia, US", lat: 39.9333, lon: -75.1333, aliases: [] },
  { name: "Baltimore, US", lat: 39.2667, lon: -76.5833, aliases: [] },
  { name: "Houston, US", lat: 29.7500, lon: -95.0000, aliases: [] },
  { name: "Corpus Christi, US", lat: 27.8000, lon: -97.4000, aliases: [] },
  { name: "Savannah, US", lat: 32.0833, lon: -81.1000, aliases: [] },

  // Middle East / Asia
  { name: "Fujairah, AE", lat: 25.1333, lon: 56.3500, aliases: ["al fujayrah"] },
  { name: "Jebel Ali, AE", lat: 25.0167, lon: 55.0667, aliases: ["jabel ali"] },
  { name: "Singapore, SG", lat: 1.2667, lon: 103.8333, aliases: [] },
  { name: "Ruwais, AE", lat: 24.1000, lon: 52.7167, aliases: [] },

  // Other
  { name: "Gibraltar, GI", lat: 36.1333, lon: -5.3500, aliases: [] },
  { name: "Las Palmas, ES", lat: 28.1333, lon: -15.4333, aliases: [] },
  { name: "Constantza, RO", lat: 44.1667, lon: 28.6500, aliases: ["constanta"] },

  // Med extra
  { name: "Tarragona, ES", lat: 41.1000, lon: 1.2333, aliases: [] },
  { name: "Castellon, ES", lat: 39.9667, lon: -0.0167, aliases: [] },
  { name: "Huelva, ES", lat: 37.2500, lon: -6.9500, aliases: [] },
  { name: "Sines, PT", lat: 37.9500, lon: -8.8667, aliases: [] },
  { name: "Koper, SI", lat: 45.5333, lon: 13.7333, aliases: [] },
  { name: "Split, HR", lat: 43.5000, lon: 16.4333, aliases: [] },

  // Black Sea
  { name: "Novorossiysk, RU", lat: 44.7167, lon: 37.7667, aliases: [] },
  { name: "Tuapse, RU", lat: 44.1000, lon: 39.0667, aliases: [] },

  // Baltic extra
  { name: "Tallinn, EE", lat: 59.4500, lon: 24.7500, aliases: [] },
  { name: "Klaipeda, LT", lat: 55.7167, lon: 21.1000, aliases: [] },
  { name: "Porvoo, FI", lat: 60.3000, lon: 25.6500, aliases: ["neste", "sköldvik"] },

  // NW Europe extra
  { name: "Le Havre, FR", lat: 49.4833, lon: 0.1000, aliases: [] },
  { name: "Dunkirk, FR", lat: 51.0500, lon: 2.3667, aliases: ["dunkerque"] },
  { name: "Hamburg, DE", lat: 53.5333, lon: 9.9667, aliases: [] },

  // UK extra
  { name: "Grangemouth, GB", lat: 56.0333, lon: -3.7000, aliases: [] },
  { name: "Teesport, GB", lat: 54.6167, lon: -1.1667, aliases: [] },
  { name: "Pembroke, GB", lat: 51.6833, lon: -4.9500, aliases: [] },

  // West Africa extra
  { name: "Monrovia, LR", lat: 6.3500, lon: -10.8000, aliases: [] },
  { name: "Freetown, SL", lat: 8.4833, lon: -13.2333, aliases: [] },

  // Caribbean / Americas extra
  { name: "Aruba, AW", lat: 12.4500, lon: -69.9667, aliases: ["san nicolas"] },
  { name: "Curacao, CW", lat: 12.1833, lon: -68.9667, aliases: ["bullenbaai", "willemstad"] },
  { name: "Point Lisas, TT", lat: 10.4000, lon: -61.4667, aliases: [] },
  { name: "St. Croix, VI", lat: 17.7000, lon: -64.7333, aliases: ["saint croix"] },
  { name: "Come-by-Chance, CA", lat: 47.8167, lon: -54.0000, aliases: [] },
  { name: "Point Tupper, CA", lat: 45.6167, lon: -61.3667, aliases: [] },

  // Middle East extra
  { name: "Yanbu, SA", lat: 24.0833, lon: 38.0500, aliases: [] },

  // Puerto Rico
  { name: "San Juan, PR", lat: 18.4500, lon: -66.1000, aliases: [] },
  { name: "Guayanilla, PR", lat: 17.9833, lon: -66.7833, aliases: [] },

  // India
  { name: "Sikka, IN", lat: 22.4333, lon: 69.8333, aliases: [] },

  // East Africa
  { name: "Mombasa, KE", lat: -4.0667, lon: 39.6667, aliases: [] },

  // USA West Coast
  { name: "Los Angeles, US", lat: 33.7333, lon: -118.2667, aliases: [] },

  // South Africa
  { name: "Cape Town, ZA", lat: -33.9000, lon: 18.4333, aliases: [] },

  // USA East Coast extra
  { name: "Portland, US", lat: 43.6567, lon: -70.2500, aliases: ["portland maine"] },
  { name: "Boston, US", lat: 42.3500, lon: -71.0500, aliases: [] },
  { name: "Norfolk, US", lat: 36.8500, lon: -76.3000, aliases: [] },
  { name: "Wilmington, US", lat: 34.2333, lon: -77.9500, aliases: [] },
  { name: "Halifax, CA", lat: 44.6333, lon: -63.5667, aliases: [] },
  { name: "San Francisco, US", lat: 37.7750, lon: -122.4183, aliases: [] },

  // Bermuda
  { name: "Hamilton, BM", lat: 32.2833, lon: -64.7833, aliases: [] },

  // Europe extra
  { name: "Aveiro, PT", lat: 40.6333, lon: -8.7500, aliases: [] },
  { name: "Bilbao, ES", lat: 43.3500, lon: -3.0333, aliases: [] },
  { name: "Falmouth, GB", lat: 50.1500, lon: -5.0667, aliases: [] },
  { name: "Thames, GB", lat: 51.4500, lon: 0.7333, aliases: [] },
  { name: "Skaw, DK", lat: 57.7333, lon: 10.5833, aliases: ["skagen"] },
  { name: "Mongstad, NO", lat: 60.8167, lon: 5.0333, aliases: [] },

  // Med extra 2
  { name: "Algiers, DZ", lat: 36.7667, lon: 3.0667, aliases: [] },
  { name: "Benghazi, LY", lat: 32.1167, lon: 20.0667, aliases: [] },
  { name: "Beirut, LB", lat: 33.9000, lon: 35.5167, aliases: [] },
  { name: "Aliaga, TR", lat: 38.8000, lon: 26.9667, aliases: [] },
  { name: "Izmit, TR", lat: 40.7667, lon: 29.9167, aliases: [] },
  { name: "Vassiliko, CY", lat: 34.7333, lon: 33.3333, aliases: [] },
  { name: "Ceuta, ES", lat: 35.8833, lon: -5.3167, aliases: [] },

  // South America
  { name: "La Libertad, EC", lat: -2.2167, lon: -80.9167, aliases: [] },

  // Canada - St. Lawrence
  { name: "Quebec, CA", lat: 46.8167, lon: -71.2000, aliases: ["quebec city"] },
  { name: "Montreal, CA", lat: 45.5000, lon: -73.5500, aliases: [] },

  // Ireland
  { name: "Dublin, IE", lat: 53.3500, lon: -6.2333, aliases: [] },
];

// Build indices
const portIndex = new Map<string, PortEntry>();
const portByName = new Map<string, PortEntry>();

for (const port of PORTS) {
  portByName.set(port.name, port);
  portIndex.set(port.name.toLowerCase(), port);
  const city = port.name.split(",")[0].trim().toLowerCase();
  if (!portIndex.has(city)) portIndex.set(city, port);
  for (const alias of port.aliases) portIndex.set(alias.toLowerCase(), port);
}

// Pre-computed data
const distances = distancesRaw as Record<string, number>;
const paths = pathsRaw as unknown as Record<string, [number, number][]>;
const handDrawnKeys = new Set<string>(
  (handDrawnKeysRaw as { keys: string[] }).keys
);

// Internal helpers
function lookupDistance(a: string, b: string): number | null {
  if (a === b) return 0;
  const key = a < b ? `${a}|${b}` : `${b}|${a}`;
  return distances[key] ?? null;
}

// Provider methods (each matches the DistanceProvider interface)

function findPort(query: string): string | null {
  const q = query.toLowerCase().trim();
  if (!q) return null;

  const exact = portIndex.get(q);
  if (exact) return exact.name;

  const commaIdx = q.indexOf(",");
  if (commaIdx > 0) {
    const city = q.slice(0, commaIdx).trim();
    const code = q.slice(commaIdx + 1).trim().toUpperCase();
    for (const port of PORTS) {
      const pCity = port.name.split(",")[0].trim().toLowerCase();
      const pCode = port.name.split(",")[1]?.trim();
      if (pCity === city && pCode === code) return port.name;
    }
  }

  const matches: PortEntry[] = [];
  for (const port of PORTS) {
    const city = port.name.split(",")[0].trim().toLowerCase();
    if (city.startsWith(q)) matches.push(port);
  }
  if (matches.length === 1) return matches[0].name;

  for (const port of PORTS) {
    if (port.name.toLowerCase().includes(q)) return port.name;
  }

  return null;
}

function searchPorts(query: string, limit = 20): PortSearchResult[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  const results: Array<{ port: PortEntry; score: number }> = [];

  for (const port of PORTS) {
    const nameLower = port.name.toLowerCase();
    const city = nameLower.split(",")[0].trim();
    let score = 0;

    if (city === q) score = 100;
    else if (city.startsWith(q)) score = 80;
    else if (nameLower.startsWith(q)) score = 70;
    else if (city.includes(q)) score = 50;
    else if (nameLower.includes(q)) score = 30;

    if (score === 0) {
      for (const alias of port.aliases) {
        if (alias === q) { score = 95; break; }
        else if (alias.startsWith(q)) { score = 75; break; }
        else if (alias.includes(q)) { score = 45; break; }
      }
    }

    if (score > 0) results.push({ port, score });
  }

  results.sort((a, b) => b.score - a.score);

  return results.slice(0, limit).map((r) => ({
    name: r.port.name,
    lat: r.port.lat,
    lon: r.port.lon,
    routingVia: null,
  }));
}

function getPortCoords(portName: string): { lat: number; lon: number } | null {
  const port = portByName.get(portName);
  if (port) return { lat: port.lat, lon: port.lon };

  const resolved = findPort(portName);
  if (resolved) {
    const p = portByName.get(resolved);
    if (p) return { lat: p.lat, lon: p.lon };
  }
  return null;
}

function checkPortAmbiguity(query: string): PortAmbiguityResult {
  const q = query.toLowerCase().trim();
  if (!q) {
    return { query, isAmbiguous: false, candidates: [], resolved: null, isAlias: false, aliasTarget: null };
  }

  const cityMatches: PortEntry[] = [];
  for (const port of PORTS) {
    const city = port.name.split(",")[0].trim().toLowerCase();
    if (city === q) cityMatches.push(port);
  }

  if (cityMatches.length === 0) {
    for (const port of PORTS) {
      for (const alias of port.aliases) {
        if (alias.toLowerCase() === q) { cityMatches.push(port); break; }
      }
    }
  }

  if (cityMatches.length > 0) {
    const candidates = cityMatches.map((p) => ({ name: p.name, lat: p.lat, lon: p.lon }));
    return {
      query,
      isAmbiguous: cityMatches.length > 1,
      candidates,
      resolved: cityMatches.length === 1 ? cityMatches[0].name : null,
      isAlias: false,
      aliasTarget: null,
    };
  }

  const exact = findPort(query);
  if (exact) {
    const p = portByName.get(exact);
    return {
      query,
      isAmbiguous: false,
      candidates: p ? [{ name: p.name, lat: p.lat, lon: p.lon }] : [],
      resolved: exact,
      isAlias: false,
      aliasTarget: null,
    };
  }

  return { query, isAmbiguous: false, candidates: [], resolved: null, isAlias: false, aliasTarget: null };
}

function getAllPorts(): PortInfo[] {
  return PORTS.map((p) => ({ name: p.name, lat: p.lat, lon: p.lon }));
}

function getSeaDistance(from: string, to: string): RouteResult {
  const fromPort = findPort(from);
  const toPort = findPort(to);

  if (!fromPort || !toPort) {
    return { totalNm: 0, legs: [], source: "not_found" };
  }

  if (fromPort === toPort) {
    return { totalNm: 0, legs: [], source: PROVIDER_NAME };
  }

  const distance = lookupDistance(fromPort, toPort);
  if (distance !== null) {
    return {
      totalNm: Math.round(distance),
      legs: [{ from: fromPort, to: toPort, distanceNm: Math.round(distance) }],
      source: PROVIDER_NAME,
    };
  }

  return { totalNm: 0, legs: [], source: "not_found" };
}

function getMultiStopDistance(portNames: string[]): RouteResult {
  if (portNames.length < 2) {
    return { totalNm: 0, legs: [], source: "not_found" };
  }

  const legs: RouteLeg[] = [];
  let totalNm = 0;

  for (let i = 0; i < portNames.length - 1; i++) {
    const result = getSeaDistance(portNames[i], portNames[i + 1]);
    if (result.source === "not_found") {
      return { totalNm: 0, legs: [], source: "not_found" };
    }
    legs.push(...result.legs);
    totalNm += result.totalNm;
  }

  return { totalNm, legs, source: PROVIDER_NAME };
}

function getRoutePath(a: string, b: string): [number, number][] | null {
  if (a === b) return null;
  const aFirst = a < b;
  const key = aFirst ? `${a}|${b}` : `${b}|${a}`;
  const stored = paths[key];
  if (!stored) return null;
  return aFirst ? stored : [...stored].reverse();
}

function isHandDrawnRoute(a: string, b: string): boolean {
  const key = a < b ? `${a}|${b}` : `${b}|${a}`;
  return handDrawnKeys.has(key);
}

export const oceanRoutingProvider: DistanceProvider = {
  name: PROVIDER_NAME,
  findPort,
  searchPorts,
  getPortCoords,
  checkPortAmbiguity,
  getAllPorts,
  getSeaDistance,
  getMultiStopDistance,
  getRoutePath,
  isHandDrawnRoute,
};
